# Build-time generator for aether/BuildIdentityGenerated.h (local builds only).
#
# Run as `cmake -P` by the aether_build_identity target on EVERY build, so the
# branch / SHA / dirty flag describe the tree actually compiled, not the tree
# that happened to be configured. The header is rewritten only when one of
# those changes, so an unchanged tree costs no recompile and no relink.
#
# Inputs (-D):
#   AETHER_BI_SOURCE_DIR  repository root
#   AETHER_BI_OUT         header to write
#   AETHER_BI_INPUTS      configure-time file that set()s AETHER_BI_LABEL and
#                         AETHER_BI_DETAILS_FILE
#   GIT_EXECUTABLE        git, may be empty
cmake_minimum_required(VERSION 3.25)

include("${AETHER_BI_INPUTS}")

function(_aether_bi_git out)
    set(_v "")
    if(GIT_EXECUTABLE)
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" ${ARGN}
            WORKING_DIRECTORY "${AETHER_BI_SOURCE_DIR}"
            OUTPUT_VARIABLE _o
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
            RESULT_VARIABLE _rv)
        if(_rv EQUAL 0)
            set(_v "${_o}")
        endif()
    endif()
    set(${out} "${_v}" PARENT_SCOPE)
endfunction()

function(_aether_bi_escape out in)
    string(REPLACE "\\" "\\\\" _s "${in}")
    string(REPLACE "\"" "\\\"" _s "${_s}")
    string(REPLACE "\r" "" _s "${_s}")
    string(REPLACE "\n" "\\n" _s "${_s}")
    set(${out} "${_s}" PARENT_SCOPE)
endfunction()

_aether_bi_git(_sha rev-parse HEAD)
_aether_bi_git(_branch rev-parse --abbrev-ref HEAD)
# Tracked files only: an untracked log or scratch file cannot change what is
# compiled (sources are listed explicitly, never globbed).
_aether_bi_git(_status status --porcelain --untracked-files=no)
if(_status STREQUAL "")
    set(_dirty false)
else()
    set(_dirty true)
endif()

set(_details "")
if(AETHER_BI_DETAILS_FILE AND EXISTS "${AETHER_BI_DETAILS_FILE}")
    file(READ "${AETHER_BI_DETAILS_FILE}" _details)
    string(STRIP "${_details}" _details)
endif()

_aether_bi_escape(_e_label "${AETHER_BI_LABEL}")
_aether_bi_escape(_e_branch "${_branch}")
_aether_bi_escape(_e_sha "${_sha}")
_aether_bi_escape(_e_details "${_details}")

set(_body
"// Generated by cmake/BuildIdentity.cmake — do not edit.
#pragma once
inline constexpr bool kAetherBuildOfficial = false;
inline constexpr const char kAetherBuildLabel[] = \"${_e_label}\";
inline constexpr const char kAetherBuildBranch[] = \"${_e_branch}\";
inline constexpr const char kAetherBuildSha[] = \"${_e_sha}\";
inline constexpr bool kAetherBuildDirty = ${_dirty};
inline constexpr const char kAetherBuildDetails[] = \"${_e_details}\";
")

# Compare without the timestamp line so the build time records when the
# identity last CHANGED, and an unchanged tree leaves the header untouched.
set(_old_body "")
if(EXISTS "${AETHER_BI_OUT}")
    file(READ "${AETHER_BI_OUT}" _old)
    string(REGEX REPLACE "inline constexpr const char kAetherBuildTime\\[\\] = \"[^\"]*\";\n" "" _old_body "${_old}")
endif()
if(NOT _old_body STREQUAL _body)
    string(TIMESTAMP _now "%Y-%m-%dT%H:%M:%SZ" UTC)
    file(WRITE "${AETHER_BI_OUT}"
        "${_body}inline constexpr const char kAetherBuildTime[] = \"${_now}\";\n")
endif()
